import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "Mags BNB",
  description: "Generated by create next app",
};

const fonts = Nunito({
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fonts.className}>
        {children}
      </body>
    </html>
  );
}
