import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/NavBar";
import ClientOnly from "./components/ClientOnly";
import Modal from "./components/Modals/Modal";

export const metadata: Metadata = {
  title: "Mags BNB",
  description: "Generated by create next app",
};

const fonts = Nunito({
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fonts.className}>
        <ClientOnly>
          <Modal
            title="Title"
            isOpen
           
          />
          <Navbar />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
